version: "3.9"

services:
  rabbitmq:
    build:
      context: docker/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    volumes:
      - ./docker/rabbitmq/lib/rabbitmq:/var/lib/rabbitmq
      - ./docker/rabbitmq/log:/var/log/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "erlang_cookie"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "pass"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"